# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json
version: "1"
root:
  repository: "local:/media/backup/restic"
  password-file: "/etc/restic/pwd_file"
  initialize: true
  lock: "/tmp/resticprofile-profile-root.lock"
  force-inactive-lock: true
  retention:
    after-backup: true
    keep-weekly: 4
    keep-daily: 3
    prune: true
  backup:
    check-before: true
    source:
      - "/"
    schedule: "*-*-* 00:00:00"
    schedule-permission: system
    schedule-priority: background
    schedule-log: profile-backup.log
    schedule-lock-wait: 15m30s
    exclude:
      - "/proc"
      - "/sys"
      - "/dev"
      - "/run"
      - "/tmp"
      - "/mnt"
      - "/media"
      - "/var/tmp"
      - "/home/jonas/onedrive"
  run-before: 'mount -o auto,suid,dev,rw,nofail,discard,prealloc,windows_names UUID=62630B3E29146A96 /media/backup'
  run-finally: 'umount /media/backup'
