# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config.json
version: "1"
default:
  repository: "local:/media/backup/restic"
  password-file: "/etc/restic/pwd_file"
  backup:
    source:
      - "/"
    schedule: "*-*-* 00:00:00"
    schedule-permission: system
    schedule-priority: background
    schedule-log: profile-backup.log
    schedule-lock-wait: 15m30s
    exclude:
      - "/sys"
      - "/dev"
      - "/tmp"
      - "/media"
      - "/mnt"
      - "/var/tmp"
