return {}

--there is a problem with <C-h> keybinings in normal mode
-- return {
--     {
--         "ms-jpq/coq_nvim",
--         branch = "coq",
--         -- config = function()
--         --     require("coq").setup()
--         -- end,
--     },
--     {
--         "ms-jpq/coq.artifacts",
--         dependencies = {
--             "ms-jpq/coq_nvim",
--         },
--         branch = "artifacts",
--     },
--     {
--         "ms-jpq/coq.thirdparty",
--         branch = "3p",
--     },
-- }
