return {
    -- {
    --     "mireq/luasnip-snippets",
    --     dependencies = { "LL3MON4D3/LuaSnip" },
    --     init = function()
    --         -- Mandatory setup function
    --         require("luasnip_snippets.common.snip_utils").setup()
    --     end,
    -- },
    -- {
    --     "L3MON4D3/LuaSnip",
    --     dependencies = {
    --         "rafamadriz/friendly-snippets",
    --     },
    --     version = "v2.*",
    --     build = "make install_jsregexp",
    --     config = function(_, opts)
    --         require("luasnip").setup(opts)
    --
    --         require("luasnip.loaders.from_vscode").lazy_load()
    --     end,
    -- },
}
